# Site settings
title: The Portfolio of Eshaan Kaul
email: eshaankaul29@gmail.com
description: "Eshaan Kaul is a Product Designer at Flipkart working on Payments & FinTech - Pay Later, Cardless Credit & Co-branded Credit Card. "
url: "http://eshaankaul.com/"
twitter_username: syskaul
github_username:  eshaankaul29

# Build settings
markdown: kramdown
theme: minima
permalink: none
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
